import type React from "react"
import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"

import CandidateSidebar from "@/components/layout/CandidateSidebar"
import { Toaster } from "@/components/ui/sonner"
import { UnifiedGuard } from "@/components/auth/UnifiedGuard"
import { ThemeProvider } from "@/providers/ThemeProvider"

import "@/styles/globals.css"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function CandidateLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <UnifiedGuard requiredUserType="candidate" fallbackPath="/sign-in">
      <ThemeProvider>
        <div className="flex min-h-screen bg-background">
          <CandidateSidebar />
          <main className="flex-1">{children}</main>
          <Toaster />
        </div>
      </ThemeProvider>
    </UnifiedGuard>
  )
}
