// This file is intentionally left mostly empty as the snapshot
// will be automatically generated by Entity Framework Core when the migration is created.
// Run: dotnet ef migrations add AddKanbanBoardColumnsAndJobPostFields

#nullable disable

namespace Recruiter.Infrastructure.Migrations
{
    using System;
    using Microsoft.EntityFrameworkCore;
    using Microsoft.EntityFrameworkCore.Infrastructure;
    using Microsoft.EntityFrameworkCore.Metadata;
    using Microsoft.EntityFrameworkCore.Migrations;
    using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
    using Recruiter.Infrastructure.Repository;

    [DbContext(typeof(RecruiterDbContext))]
    [Migration("20260210000000_AddKanbanBoardColumnsAndJobPostFields")]
    partial class AddKanbanBoardColumnsAndJobPostFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // Note: This is a simplified version. The actual snapshot will be generated
            // by running: dotnet ef migrations add AddKanbanBoardColumnsAndJobPostFields
#pragma warning restore 612, 618
        }
    }
}
